<div style="border:solid green 3px; padding: 20px">
<b>Привет Мария! 👋</b>

Меня зовут Александр Базилевич и я буду проверять твой проект. Предлагаю общаться на «ты» 🙂 Если это не удобно на ты - дай знать, и мы перейдем на "вы". Моя основная цель — не указать на совершенные тобою ошибки, а поделиться своим опытом и помочь тебе стать аналитиком данных

Вижу выполнение всех заданий и наличие выводов. Все ключевые этапы в работе выполнены, так что в целом справиться с задачей тебе удалось. Есть ещё некоторые вопросы, которые требуют твоего внимания. Комментарии по ним помечены <font color='red'>красным цветом</font> ❌. После их доработки проект будет принят. Осталось совсем немного, буду ждать твою работу на повторное ревью 🙂

Давай работать над проектом в диалоге: если ты <b>что-то меняешь</b> в проекте по моим рекомендациям — <b>пиши об этом</b>. Выбери для своих комментариев какой-то заметный цвет, так мне будет легче отследить изменения. Пожалуйста, <b>не перемещай, не изменяй и не удаляй мои комментарии</b>. Всё это поможет выполнить повторную проверку твоего проекта оперативнее

Ты также можешь реагировать на мои комментарии своими, выделяя их цветами и наиболее понравившимся тебе способом оформления, но явно  отличающимся от моих комментариев. Это нужно, чтобы не создавалась путаница 😉

<div class="alert alert-success">
<b>Комментарий ревьюера - все отлично! ✅</b>

В случае, если решение на отдельном шаге является полностью правильным 👍 Так будут отмечены удачные и элегантные решения, на которые можно опираться в будущих проектах
</div>

<div class="alert alert-warning">
<b>Комментарий ревьюера - замечания и рекомендации ⚠️</b>

В случае, когда решение на отдельном шаге станет еще лучше, если внести небольшие коррективы. Ты можешь учесть эти комментарии при выполнении будущих заданий или доработать проект сейчас (однако это не обязательно)
</div>
    
<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера - на доработку ❌</b>   

В случае, когда решение на отдельном шаге требует существенной переработки и внесения правок. Напоминаю, что проект не может быть принят с первого раза, если ревью содержит комментарии, рекомендующие доработать шаги
</div>
    
Увидев у тебя неточность, в первый раз я лишь укажу на ее наличие и дам тебе возможность найти и исправить ее. На реальной работе твой руководитель будет поступать также, и я пытаюсь подготовить тебя именно к работе аналитиком. Но если ты пока не справишься с такой задачей - при следующей проверке я дам более точную подсказку! 🤓
</div>

# Исследование надежности заемщиков

Во второй части проекта вы выполните шаги 3 и 4. Их вручную проверит ревьюер.
Чтобы вам не пришлось писать код заново для шагов 1 и 2, мы добавили авторские решения в ячейки с кодом.

## Откройте таблицу и изучите общую информацию о данных

**Задание 1. Импортируйте библиотеку pandas. Считайте данные из csv-файла в датафрейм и сохраните в переменную `data`. Путь к файлу:**

`/datasets/data.csv`

In [29]:
import pandas as pd

try:
    data = pd.read_csv('/datasets/data.csv')
except:
    data = pd.read_csv('https://code.s3.yandex.net/datasets/data.csv')

**Задание 2. Выведите первые 20 строчек датафрейма `data` на экран.**

In [30]:
data.head(20)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля

**Задание 3. Выведите основную информацию о датафрейме с помощью метода `info()`.**

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   children          21525 non-null  int64
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64
 3   education         21525 non-null  object
 4   education_id      21525 non-null  int64
 5   family_status     21525 non-null  object
 6   family_status_id  21525 non-null  int64
 7   gender            21525 non-null  object
 8   income_type       21525 non-null  object
 9   debt              21525 non-null  int64
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

## Предобработка данных

### Удаление пропусков

**Задание 4. Выведите количество пропущенных значений для каждого столбца. Используйте комбинацию двух методов.**

In [32]:
data.isna().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

**Задание 5. В двух столбцах есть пропущенные значения. Один из них — `days_employed`. Пропуски в этом столбце вы обработаете на следующем этапе. Другой столбец с пропущенными значениями — `total_income` — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца `income_type`. Например, у человека с типом занятости `сотрудник` пропуск в столбце `total_income` должен быть заполнен медианным доходом среди всех записей с тем же типом.**

In [33]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['total_income'].isna()), 'total_income'] = \
    data.loc[(data['income_type'] == t), 'total_income'].median()

### Обработка аномальных значений

**Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. таким артефактом будет отрицательное количество дней трудового стажа в столбце `days_employed`. Для реальных данных это нормально. Обработайте значения в этом столбце: замените все отрицательные значения положительными с помощью метода `abs()`.**

In [34]:
data['days_employed'] = data['days_employed'].abs()

**Задание 7. Для каждого типа занятости выведите медианное значение трудового стажа `days_employed` в днях.**

In [35]:
data.groupby('income_type')['days_employed'].agg('median')

income_type
безработный        366413.652744
в декрете            3296.759962
госслужащий          2689.368353
компаньон            1547.382223
пенсионер          365213.306266
предприниматель       520.848083
сотрудник            1574.202821
студент               578.751554
Name: days_employed, dtype: float64

У двух типов (безработные и пенсионеры) получатся аномально большие значения. Исправить такие значения сложно, поэтому оставьте их как есть. Тем более этот столбец не понадобится вам для исследования.

**Задание 8. Выведите перечень уникальных значений столбца `children`.**

In [36]:
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5])

**Задание 9. В столбце `children` есть два аномальных значения. Удалите строки, в которых встречаются такие аномальные значения из датафрейма `data`.**

In [37]:
data = data[(data['children'] != -1) & (data['children'] != 20)]

**Задание 10. Ещё раз выведите перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены.**

In [38]:
data['children'].unique()

array([1, 0, 3, 2, 4, 5])

### Удаление пропусков (продолжение)

**Задание 11. Заполните пропуски в столбце `days_employed` медианными значениями по каждого типа занятости `income_type`.**

In [39]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['days_employed'].isna()), 'days_employed'] = \
    data.loc[(data['income_type'] == t), 'days_employed'].median()

**Задание 12. Убедитесь, что все пропуски заполнены. Проверьте себя и ещё раз выведите количество пропущенных значений для каждого столбца с помощью двух методов.**

In [40]:
data.isna().sum()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

### Изменение типов данных

**Задание 13. Замените вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`.**

In [41]:
data['total_income'] = data['total_income'].astype(int)

### Обработка дубликатов

**Задание 14. Выведите на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалите их.**

In [42]:
data.duplicated().sum()

54

In [43]:
data = data.drop_duplicates()

**Задание 15. Обработайте неявные дубликаты в столбце `education`. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите их к нижнему регистру. Проверьте остальные столбцы.**

In [44]:
data['education'] = data['education'].str.lower()

### Категоризация данных

**Задание 16. На основании диапазонов, указанных ниже, создайте в датафрейме `data` столбец `total_income_category` с категориями:**

- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.


**Например, кредитополучателю с доходом 25000 нужно назначить категорию `'E'`, а клиенту, получающему 235000, — `'B'`. Используйте собственную функцию с именем `categorize_income()` и метод `apply()`.**

In [45]:
def categorize_income(income):
    try:
        if 0 <= income <= 30000:
            return 'E'
        elif 30001 <= income <= 50000:
            return 'D'
        elif 50001 <= income <= 200000:
            return 'C'
        elif 200001 <= income <= 1000000:
            return 'B'
        elif income >= 1000001:
            return 'A'
    except:
        pass

In [46]:
data['total_income_category'] = data['total_income'].apply(categorize_income)

**Задание 17. Выведите на экран перечень уникальных целей взятия кредита из столбца `purpose`.**

In [47]:
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее образование',
       'покупка жилья для сдачи', 'на покупку автомобиля', 'ремонт жилью',
       'заняться высшим образованием'], dtype=object)

**Задание 18. Создайте функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, в который войдут следующие категории:**

- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

**Например, если в столбце `purpose` находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`.**

**Используйте собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучите данные в столбце `purpose` и определите, какие подстроки помогут вам правильно определить категорию.**

In [48]:
def categorize_purpose(row):
    try:
        if 'автом' in row:
            return 'операции с автомобилем'
        elif 'жил' in row or 'недвиж' in row:
            return 'операции с недвижимостью'
        elif 'свад' in row:
            return 'проведение свадьбы'
        elif 'образов' in row:
            return 'получение образования'
    except:
        return 'нет категории'

In [49]:
data['purpose_category'] = data['purpose'].apply(categorize_purpose)

<div class="alert alert-success">
<b>Комментарий ревьюера - все отлично! ✅ </b>

Да, авторское решение и вправду очень изящно! Давай посмотрим что получилось у тебя!
</div>

## Исследуйте данные и ответьте на вопросы

**Задание 19. Есть ли зависимость между количеством детей и возвратом кредита в срок?**

In [50]:
# Ваш код будет здесь. Вы можете создавать новые ячейки.

children = data.loc[data['children'] != 0]
# print(children.groupby('children')['debt'].agg('mean')) или
data_children_pivot = children.pivot_table(index = 'children', values = 'debt', aggfunc = 'mean')
print(data_children_pivot)
data_pivot = data.pivot_table(index = 'children', values = 'debt', aggfunc = 'mean')
print(data_pivot)

              debt
children
1         0.092327
2         0.094542
3         0.081818
4         0.097561
5         0.000000
              debt
children
0         0.075353
1         0.092327
2         0.094542
3         0.081818
4         0.097561
5         0.000000

In [51]:
def pivot_tables(data, category):
    data_temp = data.pivot_table(index=category, values='debt', aggfunc = ['count', 'sum', 'mean'])
    data_temp.columns = ['Всего кредитополучателей', 'Всего должников', 'Доля должников']
    display(data_temp)

children = data.loc[data['children'] != 0]
# print(children.groupby('children')['debt'].agg('mean')) или
#data_children_pivot = children.pivot_table(index = 'children', values = 'debt', aggfunc = ['count', 'sum', 'mean'])
pivot_tables(children, 'children')
print()
#data_pivot = data.pivot_table(index = 'children', values = 'debt', aggfunc = ['count', 'sum', 'mean'])
pivot_tables(data, 'children')

          Всего кредитополучателей  Всего должников  Доля должников
children
1                             4809              444        0.092327
2                             2052              194        0.094542
3                              330               27        0.081818
4                               41                4        0.097561
5                                9                0        0.000000

          Всего кредитополучателей  Всего должников  Доля должников
children
0                            14107             1063        0.075353
1                             4809              444        0.092327
2                             2052              194        0.094542
3                              330               27        0.081818
4                               41                4        0.097561
5                                9                0        0.000000

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера - на доработку ❌</b>   

Твой код дает правильный результат. Но он неоптимален, поэтому сводную таблицу лучше сделать так, чтобы чтобы агрегация имела вид `aggfunc=['count', 'sum', 'mean']`. Что касается 'Всего кредитополучателей' - это `sum`. 'Всего должников' - это `count`. А долю должников это `mean`. Таким образом внеси правки в `data.pivot_table`
     
И еще, мы 4 раза выполняем один и тот же алгоритм. Поэтому давай попробуем сделать функцию на вход которой принимается переменная категория, далее делаем сводную таблицу во временный датасет `data_temp`, переименовываем столбцы ['Всего кредитополучателей', 'Всего должников','Доля должников'] и с помощью функции `display(data_temp)` выводим полученный результат
  
Попробуй это сделать в новых ячейках чтобы сравнить полученные данные

</div>

<div class="alert alert-warning">
<b>Комментарий 2 ревьюера - замечания и рекомендации ⚠️</b>

Отлично! Спасибо что сделала функцию! По ней два комментария:
1) функция выводит на экран сводную таблицу, поэтому что то возвращать она не должна
2) при переименовании у тебя получился мультииндекс (это некомфортное свойство сводной таблицы), чтобы ее полностью убрать сделай не замену, а переименование столбцов таким образом: `data_temp.columns = ['Всего кредитополучателей', 'Всего должников', 'Доля должников']`
</div>

**Вывод:** Если судить по людям, имеющим не менее одного ребенка, то нельзя утверждать, что существует ясная корреляция между количеством детей и возвратом кредита в срок. Однако, если обратить внимание на вторую таблицу, то можно сделать вывод, что в целом наличие детей несущественно увеличивает вероятность того, что кредит не будет возвращен вовремя.
Для того, чтобы точно ответить на этот вопрос, необходимо обратиться к более обширной выборке. Так, мы имеем всего 50 человек, у которых 4 и более детей, что несопоставимо с количеством людей, у которых детей меньше.
Таким образом, если не учитывать категорию людей, имеющих 5 детей, то согласно второй таблице, лица, имеющие детей, с большей вероятностью не вернут кредит в срок. Напротив, люди, не имеющие детей, реже имеют задолжности.

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера - на доработку ❌</b>   

Надеюсь, что на предидущем этапе удалось сделать функцию и тогда в новой ячейке вызови функцию и посмотрим, что получилось

Важно в выводе посмотреть не только на процент, но и на количество в каждой категории. Тогда и вывод будет точнее как дет или их отсутствие влияют на возврат кредита   
</div>

<div class="alert alert-block alert-danger">
<b>Комментарий 2 ревьюера - на доработку ❌</b>   

Так, давай поправим все же вывод.  Не смотри на первую таблицу. Что показывает вторая? Не учитывай количство детей больше 5 - их крайне мало и брать в расчет не надо. Какой вывод напрашивается сам собой? 
</div>

<div class="alert alert-success">
<b>Комментарий 3 ревьюера - все отлично! ✅ </b>

Спасибо, что выполнила все рекомендаци! Да, вывод правильный - люби без детей реже имеют проблемы с возвратом кредита!
</div>

**Задание 20. Есть ли зависимость между семейным положением и возвратом кредита в срок?**

In [52]:
data_family_status_pivot = data.pivot_table(index='family_status', values='debt', aggfunc='mean')
print(data_family_status_pivot)
data_2 = data
data_2.loc[(data['family_status'] == 'Не женат / не замужем') | (data['family_status'] == 'в разводе') |
          (data['family_status'] == 'вдовец / вдова'), 'family_status_classified'] = 0
data_2.loc[(data['family_status'] == 'гражданский брак') | (data['family_status'] == 'женат / замужем'),
           'family_status_classified'] = 1
print()
data2_family_pivot = data_2.pivot_table(index='family_status_classified', values='debt', aggfunc='mean')
print(data2_family_pivot)

                           debt
family_status
Не женат / не замужем  0.097639
в разводе              0.070648
вдовец / вдова         0.066246
гражданский брак       0.092861
женат / замужем        0.075575

                              debt
family_status_classified
0.0                       0.085089
1.0                       0.079942

In [53]:
pivot_tables(data, 'family_status')
print()
pivot_tables(data_2, 'family_status_classified')

,Всего кредитополучателей,Всего должников,Доля должников
family_status,,,
Не женат / не замужем,2796,273,0.097639
в разводе,1189,84,0.070648
вдовец / вдова,951,63,0.066246
гражданский брак,4146,385,0.092861
женат / замужем,12266,927,0.075575

,Всего кредитополучателей,Всего должников,Доля должников
family_status_classified,,,
0.0,4936,420,0.085089
1.0,16412,1312,0.079942

**Вывод:** Первая таблица не очень показательна в отношении того, существует ли корелляция между семейнм положением и возвратом кредита в срок. Категориями лиц, наиболее часто получающими задолжности, являются еще неженатые люди и люди, состоящие в гражданском браке.
Согласно исследованию зависимости между тем, состоят ли люди в браке или по каким-либо причинам нет, можно сделать вывод о том, что вторые незначительно чаще имеют задолжности.
Однако число людей, состоящих в отношениях и не состоящих, несопоставимо (различается почти в 4 раза), что может в некоторой степени негативно влиять на достоверность результатов исследования. Также в первой таблице категории людей "вдовец / вдова" и "в разводе" слишком малочисленны и не дают точной информации.

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера - на доработку ❌</b>   

Здесь и далее тоже важно в выводе посмотреть не только на процент, но и на количество в каждой категории. Тогда и вывод будет точнее   
</div>

<div class="alert alert-success">
<b>Комментарий 2 ревьюера - все отлично! ✅ </b>

Спасибо за внесенные правки, сейчас выводы наглядны и обоснованы!
</div>

**Задание 21. Есть ли зависимость между уровнем дохода и возвратом кредита в срок?**

In [54]:
categorized_income_pivot_table = data.pivot_table(index='total_income_category', values='debt', aggfunc='mean')
print(categorized_income_pivot_table)

                           debt
total_income_category
A                      0.080000
B                      0.070602
C                      0.084891
D                      0.060172
E                      0.090909

In [55]:
pivot_tables(data, 'total_income_category')

,Всего кредитополучателей,Всего должников,Доля должников
total_income_category,,,
A,25,2,0.080000
B,5014,354,0.070602
C,15938,1353,0.084891
D,349,21,0.060172
E,22,2,0.090909

**Вывод:** Согласно данным, зависимость между уровнем дохода и возвратом кредита в срок отсутствует. Лица, наиболее часто имеющие должности, имеют категории C и E относительно уровня их доходов. Однако люди, попадающие в категорию A, также довольно часто не возвращают кредит в срок.
В категории Е ситуация наихудшая. Можно сделать вывод о том, что люди с небольшим доходом наиболее часто имеют задолжности.

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера - на доработку ❌</b>   

Сложно делать выводы только по средним, но даже по ним видно, что в категории Е наихудшая ситуация. Кто эти люди?  
</div>

<div class="alert alert-success">
<b>Комментарий 2 ревьюера - все отлично! ✅ </b>

Вот! Совсем другое дело! Молодец! Да, пускай вывод тривиален, но мы его получили путем анализа данных!
</div>

**Задание 22. Как разные цели кредита влияют на его возврат в срок?**

In [56]:
# Ваш код будет здесь. Вы можете создавать новые ячейки.
categorized_purpose_pivot_table = data.pivot_table(index='purpose_category', values='debt', aggfunc='mean')
print(categorized_purpose_pivot_table)

                              debt
purpose_category
операции с автомобилем    0.093436
операции с недвижимостью  0.072531
получение образования     0.092504
проведение свадьбы        0.078744

In [57]:
pivot_tables(data, 'purpose_category')

,Всего кредитополучателей,Всего должников,Доля должников
purpose_category,,,
операции с автомобилем,4281,400,0.093436
операции с недвижимостью,10754,780,0.072531
получение образования,3989,369,0.092504
проведение свадьбы,2324,183,0.078744

**Вывод:** Кредит, взятый с целью получения образования или проведения операций с автомобилем, с большей вероятностью не будет возвращен в срок. Напротив, кредит, взятый с целью проведения операций с недвижимостью, с наибольшей вероятностью не будет просрочен. Однако можно отметить, что сильная зависимость между тем, с какой целью взят кредит и возвращен ли он в срок, отсутствует.

<div class="alert alert-success">
<b>Комментарий ревьюера - все отлично! ✅ </b>

Справедливые выводы, молодец!
</div>

**Задание 23. Приведите возможные причины появления пропусков в исходных данных.**

*Ответ:* Пропуски в исходных данных появляются вследствие отсутствия информации по количеству проработанных дней и размеру общего дохода. Важно отметить, что количество пропусков в соответствующих столбцах совпадает. Из вышесказанного можно сделать вывод, что отсутствует информация о должностях и занятости определенных лиц.
Люди, для которых в столбцах 'total income' и 'days employed' установлены пропуски могут быть безработными, пенсионерами, могут намеренно не указывать эти данные о себе, возможно также, что учет трудового стажа и общего дохода не ведется.

<div class="alert alert-warning">
<b>Комментарий ревьюера - замечания и рекомендации ⚠️</b>

Давай попробуем представить по каким причинам случились пропуски в данных?

</div>

<div class="alert alert-success">
<b>Комментарий 2 ревьюера - все отлично! ✅ </b>

Да, все верно - люди могут по каким то своим личным причинам не указывать данные!
</div>

**Задание 24. Объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.**

*Ответ:* Выбросы значений сильно искажают реальную картину для категорий людей, если пользоваться средним арифметическим. Именно медианное значение наиболее точно характеризует значения для той или иной категории, является наиболее близким к большинству значений из группы. Среднее значение, напротив, некорректно характеризует данные, когда некоторые значения сильно выделяются среди большинства.

<div class="alert alert-warning">
<b>Комментарий ревьюера - замечания и рекомендации ⚠️</b>

Полностью согласен, но почему среднее арифметическое искажает данные?

</div>

<div class="alert alert-success">
<b>Комментарий 2 ревьюера - все отлично! ✅ </b>

Да, все так! Мы обычно говорим так: вбросы сильно влияют на среднее арифмитическое
</div>

## Общий вывод.

В исходном датасете была представлена информация о 21525 людях, и для каждого из них уточняющая информация об уровне образования, семеном положении, трудовом стаже, наличии задолжностей в прошлом и т. д., однако данные содержали существенное количество пропусков, дупликаты и аномальные значения. После их обработки и группировки было проведено исследование относительно того, существует ли зависимость между вероятностью возвращения кредита в срок и количеством детей, семейным положением, целью взятия кредита, уровнем дохода.
В общем и в целом, количество детей, семейное положение, цель, с которой взят кредит и уровень дохода не оказывают существенного влияния на вероятность возвращения кредита в срок. Можно, однако, отметить, что наличие детей, состояние в браке, получение кредита с целью получения образования или проведения операций с автомобилем и уровень дохода ниже среднего, а особенно, все эти факторы в совокупности, будут увеличивать вероятность получения некоторым лицом задолжности. Необходимо также отметить, что для большой части людей отсутствуют данные по уровню дохода и стажу работы, что может несущественно искажать результаты исследования. Кроме того, в разных категориях людей могут быть несопоставимые числа, не дающие достоверной информации.
Решающими факторами, имеющими наибольшее влияние на вероятность возвращения кредита в срок, можно назвать уровень дохода и цель, с которой берется кредит. Так, например, кредиты, взятые с целью проведения операций с недвижимостью, и кредиты, взятые людьми со средним и выше среднего уровнем дохода, почти всегда возвращаются вовремя.

<div class="alert alert-block alert-danger">
<b>Комментарий ревьюера - на доработку ❌</b>   

По своей работе скажу - выводы самое главное, что читает заказчик или руководство. Добавь описание датасета, какие в нем были особенности, какие перечисли кратко  какие выводы получены по результатам анализа 
</div>

<div class="alert alert-warning">
<b>Комментарий 2 ревьюера - замечания и рекомендации ⚠️</b>

Вывод прекрасен! На будущее чтобы легче его было читать делай форматирование, абзацы и списки!

</div>

<div class="alert alert-info">

<h3> Резюме по проекту ❌ <a class="tocSkip"> </h3>
  
Я вижу хорошую работу с достойными выводами! Давай поправим сводную таблицу, добавим описание данных в финальный вывод и, если получится, сделаем функцию для более простого вывода результатов
  
Остались обязательно сделать небольшие доработки, чтобы принять проект:
* сделать сводную таблицу
* посмотреть на выводы с позиции количества данных
* добавить описание данных и работу с ними в финальный вывод  

Спасибо! Так держать 👍 Жду твой проект на повторное ревью!
</div>

<div class="alert alert-info">

<h3> Резюме 2 по проекту ❌ <a class="tocSkip"> </h3>
  
Молодец! Проведена прекрасная работа и сделаны почти все верные выводы! Осталось только сформулировать точный вывод по признаку дети. Отдельно хочу сказать спасио за сделанную функцию! 
  
Осталась одна доработка:
* сделать вывод по обслуживанию кредита в зависимости от наличия/отсутствия детей

Спасибо! Так держать 👍 Жду твой проект на повторное ревью!
</div>

<div class="alert alert-info">

<h3> Резюме 3 по проекту ✅<a class="tocSkip"> </h3>
  
Мария, спасибо что поправила выводы и учла все мои рекомендации! На будущее - уделяй больше внимания структуре финального вывода, он крайне важен

Работа принята! Удачи с следующими проектами 🍀
</div>