<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера</b></font>

Привет Мария! Меня зовут Марат, и я буду твоим ревьюером. Спешу сообщить что все ключевые этапы в работе выполнены,  с задачей тебе удалось справиться. По поводу обращения - в IT сфере принято общаться на «ты» :) Но, если привычней на «вы», дай знать. Как ревьюера моя задача помочь тебе в развитии, дав хорошие советы. Я внимательно посмотрю твой код, ознакомлюсь с твоими выводами и оставлю комментарии. Где то могу предложить небольшие исправление в коде, но ненавязчиво. Где потребуются уточнения, я оставлю много наводящих вопросов. Они помогут тебя с поиском верного решения.

Все мои комментарии размечены по цветам, для лучшего восприятия. 
    
<div class="alert alert-success">Зеленым цветом и 👍, словом «Успех» отмечены особо удачные и элегантные решения, которыми ты можешь гордиться. </div>
        
<div class="alert alert-warning">Желтым и 🤔, словом «Совет», помечены решения у которых есть альтернативные решения, более оптимальные. Ты можешь найти их сразу и доработать проект, или отложить это на потом, для будущих проектах. Проект будет принят и без их доработки. </div>
        
<div class="alert alert-danger"> Красным цветом и значком ❌, словом «Ошибка» помечу твои решения, на которые стоит обратить внимание прежде всего. После их доработки проект будет принят. </div>
        
Залог успеха - работа сообща, взаимное уважение и работа в диалоге. Поэтому, помечай свои ответные комментарии на мои реплики заметным цветом или курсивом, так мне будет легче их отслеживать. Пожалуйста, не изменяй и не удаляй мои комментарии. Все это поможет выполнить повторную проверку быстрей.

</div>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:


Вступление в работу очень важно, так человек, который смотрит твой проект (и на работе в том числе) будет сразу введен в курс дела.





</div>

## Загрузка данных

In [1]:
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
import numpy as np

Посмотрим на данные

In [2]:
df = pd.read_csv('/datasets/insurance.csv')
df.head()

   Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [3]:
features = df.drop('Страховые выплаты', axis=1)
target = df['Страховые выплаты']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Пол                5000 non-null   int64
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64
 4   Страховые выплаты  5000 non-null   int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB

In [5]:
df.describe()

               Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

In [6]:
print(features.shape)

(5000, 4)

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍: 
    
EDA проведено.  


    
<div class="alert alert-warning">


Совет 🤔: 
    
    

- Кроме того можно посмотреть на    корреляцию признаков.  Я у тебя проверял "введение...", наверное уже спрашивал, тем не менее спрошу ещё раз, тем более есть некоторые дополнительные детали: "Известно ли тебе понятие мультиколлиниарность, какие 2 типа проблемы вызывает она и для каких моделей, и почему для данного проекта было бы интересно на нее глянуть? "

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** не изменится

**Обоснование:** 

Для того, чтобы доказать, что качество линейной регрессии не изменится, необходимо доказать, что выражение $ a_1 = XPw = XP @((XP).T @ (XP))^{-1} @ (XP).T @ y $ равно $ a = Xw = X @(X.T @ X)^{-1} @ X.T @ y $,
для этого применим свойство матриц $ (AB).T = B.T @ A.T $

 $ XP @ ((XP).T @ XP)^{-1} @ (XP).T @  y = XP @ (P.T @  X.T @ XP)^{-1} @  P^T @  X^T @ y = XP @ (P.T @ (X.T @ XP))^{-1} @ P.T  @ X.T @ y $
 
 Теперь можно использовать следующее свойство матриц: 
 
 $ (AB)^{-1} = B^{-1} @ A^{-1} $, при том, что обратной матрицы $ X^{-1} $ не существует
 
$ XP @ (P.T @ (X.T @ XP))^{-1} @ P.T @X.T @ y = XP @ (X.T @ XP)^{-1} @ (P.T)^{-1} @ P.T @ X.T @ y  = XP @ P^{-1} @ (X.T  @ X)^{-1} @ (P.T)^{-1} @ P.T @ X.T @ y $
 
 Заменим $ P @ P^{-1} на E, так как A @ A^{-1} = E $
 
 $ XP @ P^{-1} @ (X.T @ X)^{-1} @ (P.T)^{-1} @ P.T @ X.T @ y = X @ E @ (X.T @ X)^{-1} @ E @ X.T @ y $
 
 Очевидно, что AE = EA = A, следовательно
 
$ X @ E @ (X.T @ X)^{-1} @ E @ X.T @ y = X @ (X.T @ X)^{-1} @ X.T $
 
 Тогда выражение a_1 действительно равно a.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:

Типичные ошибки - неверно применяют  свойства обращения и транспонирования матриц, не учитывают квадратность матриц при обращении. Но тебя не проведешь )


    
<div class="alert alert-warning">



Совет 🤔:    
    
    
    
  
Есть ещё один способ доказательства   когда мы берём
    
    
$$
w = \arg\min_w MSE(Xw, y)
$$
    
  
и     
    
$$
w_P = \arg\min_w MSE(XPw_p, y)
$$  
    
    
И делая  замену    w_p, видим что задача  
    
$$
\arg\min_w MSE(XPw_p, y)
$$
    
сводится к     
  
    
$$
\arg\min_w MSE(Xw, y)
$$    


Осталось только догадаться какую замену мы делаем  

  
</div>


<div class="alert alert-danger">
<font size="5"><b>Комментарий ревьюера</b></font>

Ошибка ❌:
    
1

  
Нет ответа на "как связаны параметры линейной регрессии в исходной задаче и в преобразованной"

Какое соотношение между $w$ и $w_p$?
    
    
Где   



$$
w = (X^T X)^{-1} X^T y
$$
    
    
$$
w_P = ((XP)^T XP)^{-1} (XP)^T y
$$   




2

    
Очень тяжело разбирать записи в таком виде,  почему бы не использовать  специальную запись используя `$`

PWp = W

## Алгоритм преобразования

**Алгоритм**

Умножение матрицы признаков на любую обратимую матрицу


<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:


Принято

**Обоснование**

Так как выше было доказано, что два выражения тождественны, можно утверждать, что предсказания модели линейной регрессии не изменится, если провести преобразование данных, а следовательно и качество модели не ухудшится.

## Проверка алгоритма

Сначала посмотрим на качество модели при неизмененных признаках.

In [7]:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
r2 = r2_score(target, predictions)
print(r2)

0.4249455028666801

Теперь сгененируем рандомную матрицу

In [8]:
np.random.seed(42)
random_matrix = np.random.randint(1, 40, size=(4, 4))
print(random_matrix)

[[39 29 15  8]
 [21 39 19 23]
 [11 11 24 36]
 [24  3 22  2]]

Убедимся, что сгенерированная матрица обратимая

In [9]:
while np.linalg.det(random_matrix) == 0:
    random_matrix = np.random.randint(1, 40, size=(4,4))

<div class="alert alert-danger">
<font size="5"><b>Комментарий ревьюера</b></font>

Ошибка ❌:

    
    
А откуда мы знаем что сгенерированная матрица обратимая (вероятность невысокая, но она есть)? Это нужно проверять, и если она получится не обратимой, генерировать опять    

    
    
<div class="alert alert-warning">



Совет 🤔:


- Можно использовать функцию с конструкцией while: будем генерировать случайные матрицы, пока не получим с детерминантом не равным нулю или можно использовать рекурсию (Но для этого надо убрать np.random.seed(42))
    
    
    
    

    
- что насчет универсальности кода? Сейчас ты цифрой определяешь размерность случайной матрички, почему бы не написать код, который отработает для любой размерности матрицы обьект-признак?      
      
    
    
</div>

Произведем преобразоание данных

In [10]:
features_modified = features @ random_matrix

In [11]:
print(features_modified.shape)

(5000, 4)

In [12]:
features_modified.head()

          0         1          2          3
0  546524.0  547231.0  1191216.0  1786553.0
1  418990.0  419797.0   912896.0  1369060.0
2  231609.0  232131.0   504551.0   756667.0
3  459189.0  459525.0  1001243.0  1501687.0
4  287727.0  288221.0   626947.0   940252.0

Из преобразованных данных нельзя догататься о конфиденциальной информации клиентов страховой компании.

Теперь посчитаем r2 для преобразованных данных.

In [13]:
model = LinearRegression()
model.fit(features_modified, target)
predictions_modified = model.predict(features_modified)
r2_modified = r2_score(target, predictions_modified)
print(r2_modified)

0.42494550286667754

Показатель r2 совершенно не изменился. Он примерно равен 0.42 как до преобразования, так и после. Качество модели не ухудшилось, а данные стали защищенными.

ВЫВОДЫ

Умножение некоторой матрицы на рандомно сгенерированную обратимую матрицу не повлияет на качество модели линейной регрессии.

Такая техника может использоваться для зашифровки данных, так как из преобразованных данных невозможно вывести конфиденциальную информацию.



<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:
    
Все сошлось.

<div class="alert alert-warning">


Совет 🤔: 
    
    

    
- каноны ML - когда мы моделируем, разбиваем датасет на несколько, используя train для обучения и test для проверки, опять же это никак не изменит выводы, но каноны стоит уважать




<div class="alert alert-danger">
<font size="5"><b>Комментарий ревьюера</b></font>

Ошибка ❌:

Мария, было бы замечательно, в конце немножко о данных, работе с ними, моделировании и полученных результатах, доказательствах. Это важно потому что когда проект захочет посмотреть будущий работодатель (или начальник), у него может не быть времени на подробный разбор кода. Вероятнее всего он бегло просмотрит код, а из общего вывода захочет получить представление о всей работе. Вырабатывай рефлексы правильного формления проектов )


</div>


<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера</b></font>


Мария, у тебя старательно выполненная работа, все четко, осмысленно. Отмечаю уровень твоей программистской подготовки. 



Я оставил небольшие советы и вопросики (если есть время и желание можешь воспользоваться/ответить)
    


Обязательное к исправлению:





- выводим соотношение между  𝑤  и  𝑤𝑝 
 
    




- нет проверки на обратимость 
    
    
- рекомендую добавить общий вывод (лицо проекта)



    
    
Жду исправлений, для принятия проекта. Если какие то вопросы, то сразу спрашивай ) 

</div>

ОБЩИЙ ВЫВОД

Данные представлены 5000 строками и 5 столбцами, тип всех признаков - количественный. Один из столбцов представляет собой таргет - это страховые выплаты.

В ходе проекта было доказано, что предсказания модели линейной регрессии не будут отличаться от изначальных, если умножить их на рандомно сгенерированную обратимую матрицу.

Таким образом, подобное умножение является способом зашифровки конфиденциальной информации клиентов. Признаки, прошедшие через такую процедуру зашифровки, не дают никакой информации об изначальных данных.

В ходе проекта данные были умножены на рандомно сгенерированную обратимую матрицу. Метрика R2 была посчитана как для изначальных, так и для преобразованных данных. Показатель был одним и тем же в обоих случаях, что снова доказывает, что модель линеной регрессии делает на преобразованных данных такие же точные предсказания, как и на изначальных.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [ ]  Весь код выполняется без ошибок
- [ ]  Ячейки с кодом расположены в порядке исполнения
- [ ]  Выполнен шаг 1: данные загружены
- [ ]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [ ]  Указан правильный вариант ответа
    - [ ]  Вариант обоснован
- [ ]  Выполнен шаг 3: предложен алгоритм преобразования
    - [ ]  Алгоритм описан
    - [ ]  Алгоритм обоснован
- [ ]  Выполнен шаг 4: алгоритм проверен
    - [ ]  Алгоритм реализован
    - [ ]  Проведено сравнение качества моделей до и после преобразования